name: demo using variables

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/login@v1
      with:
        environment: azurecloud
        allow-no-subscriptions: true
        tenant-id: ${{vars.AZURE_TENANT_ID}}
        client-id: ${{vars.AZURE_UAMI_CLIENT_ID}}
        audience: api://AzureADTokenExchange
    - id: getSecretFromKeyVault
      uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: ${{vars.AZURE_KEYVAULT_NAME}}
        secrets: 'demosecret'
    - name: Echo the secret
      run: |
        echo "My Secret: ${{ steps.getSecretFromKeyVault.outputs.demosecret }}" | base64
    - name: Azure CLI Script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az keyvault secret show --vault-name ${{vars.AZURE_KEYVAULT_NAME}} --name 'demosecret' | jq -r '.value'
